/* Generated by 'StoryboardScenesObjc' script as part of a Run Script Build Phase. Changes WILL BE OVERWRITTEN */

#import <Foundation/Foundation.h>
#import "MWObjcPage1ViewController.h"
#import "MWObjcPage2ViewController.h"

@class MWPage2ViewController;
@class MWPage1ViewController;


@interface MWStoryboards : NSObject


/* -- MainStoryboard controllers -- */ 

+ (MWPage2ViewController *)instantiateSwiftPage2;
+ (MWPage1ViewController *)instantiateSwiftPage1;


/* -- ObjcStoryboard controllers -- */ 

+ (MWObjcPage1ViewController *)instantiateObjcPage1;
+ (MWObjcPage2ViewController *)instantiateObjcPage2;

@end