/* Generated by 'MWStoryboardScenes' script as part of a Run Script Build Phase. Changes WILL BE OVERWRITTEN */

#import "MWStoryboards.h"


@implementation MWStoryboards

#pragma mark -  MainStoryboard instantiators

+ (MWPage2ViewController *)instantiateSwiftPage2 {
    return (MWPage2ViewController *)[[MWStoryboards MainStoryboard] instantiateViewControllerWithIdentifier:@"swiftPage2"];
}

+ (MWPage1ViewController *)instantiateSwiftPage1 {
    return (MWPage1ViewController *)[[MWStoryboards MainStoryboard] instantiateViewControllerWithIdentifier:@"swiftPage1"];
}


#pragma mark -  ObjcStoryboard instantiators

+ (MWObjcPage1ViewController *)instantiateObjcPage1 {
    return [[MWStoryboards ObjcStoryboard] instantiateViewControllerWithIdentifier:@"objcPage1"];
}

+ (MWObjcPage2ViewController *)instantiateObjcPage2 {
    return [[MWStoryboards ObjcStoryboard] instantiateViewControllerWithIdentifier:@"objcPage2"];
}


#pragma mark - Private storyboard initializers

+ (UIStoryboard *)MainStoryboard {
    NSString *identifier = UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad ? @"MainStoryboard_iPad" : @"MainStoryboard_iPhone";
    return [UIStoryboard storyboardWithName:identifier bundle:nil];
}

+ (UIStoryboard *)ObjcStoryboard {
    NSString *identifier = UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad ? @"ObjcStoryboard_iPad" : @"ObjcStoryboard_iPhone";
    return [UIStoryboard storyboardWithName:identifier bundle:nil];
}


@end